"use client"

import { useMemo, useState } from "react"
import { Button } from "@/components/ui/button"
import { Label } from "@/components/ui/label"
import { Textarea } from "@/components/ui/textarea"
import { RadioGroup, RadioGroupItem } from "@/components/ui/radio-group"
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card"
import { toast } from "sonner"

export type HtmlInsertMode = "replace" | "append" | "prepend"

interface HtmlAssistantCardProps {
  onInsert: (html: string, mode: HtmlInsertMode) => boolean
}

const rulesForAi = [
  "Target editor: Tiptap (ProseMirror-based rich text editor).",
  "Generate HTML that is compatible with Tiptap parsing and this editor's enabled extensions.",
  "Use only trusted HTML that maps to this editor's enabled extensions.",
  "General contract:",
  "- Keep markup clean (avoid excessive blank text nodes/newlines between block tags).",
  "- Prefer standard semantic tags unless a custom data-* contract is required below.",
  "Paragraph and alignment:",
  "- Use <p> for normal text blocks.",
  "- Alignment is read from style (for example: style='text-align:center').",
  "Custom heading node:",
  "- Use h1..h4 with data-custom-heading and data-level='1..4'.",
  "- Optional icon label: span[data-custom-heading-icon][data-level][data-icon].",
  "- Keep heading icon span as the first child in heading when possible.",
  "- Plain h1..h4 are still valid but custom icon metadata requires the data-* attributes above.",
  "Lists and tasks:",
  "- Bullet/ordered lists: <ul>/<ol> with <li>.",
  "- Task list: <ul data-type='taskList'> with <li data-type='taskItem' data-checked='true|false'>.",
  "Callout node:",
  "- Use blockquote[data-callout][data-type='info|warning|success|error|note|clinical'].",
  "- Optional header child: div[data-callout-header][data-type][data-icon][data-label].",
  "- Header text is recommended (for example: 'ℹ️ Note').",
  "Code and inline formatting:",
  "- Bold/italic/strike/underline: <strong>, <em>, <s>, <u>.",
  "- Inline code: <code>inline</code>; code block: <pre><code>...</code></pre>.",
  "- Sub/superscript: <sub> and <sup>.",
  "- Links: <a href='...'>...</a>.",
  "Question template node:",
  "- Wrapper: div[data-question-template].",
  "- Section: div[data-question-section][data-title].",
  "- Optional helper wrappers generated by editor are supported: div[data-question-section-header], div[data-question-section-content].",
  "- Suggested default section titles for question explanation template (not required, you can add/remove/reorder):",
  "  1) 📌 The Correct Answer:",
  "  2) 📚 Full Topic Text From Source:",
  "  3) 👨‍⚕️ Doctor's Explanation:",
  "  4) ❌ Why other options are incorrect:",
  "  5) 🔍 Context:",
  "Text styling marks:",
  "- Text color: inline style color (for example: <span style='color:#2563eb'>text</span>).",
  "- Font size: inline style font-size (for example: <span style='font-size:18px'>text</span>).",
  "- Highlight: prefer <mark data-color='...'>text</mark>.",
  "- Recommended highlight color values: var(--tt-color-highlight-green), var(--tt-color-highlight-blue), var(--tt-color-highlight-red), var(--tt-color-highlight-purple), var(--tt-color-highlight-yellow).",
  "- Additional valid palette values include: var(--tt-bg-color), var(--tt-color-highlight-gray), var(--tt-color-highlight-brown), var(--tt-color-highlight-orange), var(--tt-color-highlight-pink).",
  "Media and embeds:",
  "- Images: <img src='...' alt='...'>.",
  "Image upload placeholder node:",
  "- div[data-type='image-upload'].",
  "Horizontal rule wrapper:",
  "- div[data-type='horizontalRule'] containing hr.",
  "Tables:",
  "- Use <table><tbody><tr><td>...</td></tr></tbody></table> (thead/th optional).",
  "YouTube embed:",
  "- Use an iframe-compatible youtube embed URL (youtube.com/embed/... or youtu.be transformed to embed).",
  "- Width/height can be included; this editor config defaults to 640x360 when inserted from toolbar.",
]

export default function HtmlAssistantCard({ onInsert }: HtmlAssistantCardProps) {
  const [htmlSnippet, setHtmlSnippet] = useState("")
  const [insertMode, setInsertMode] = useState<HtmlInsertMode>("append")

  const rulesText = useMemo(() => rulesForAi.join("\n"), [])

  const handleInsert = () => {
    if (!htmlSnippet.trim()) {
      toast.error("Please add HTML before inserting")
      return
    }

    const inserted = onInsert(htmlSnippet, insertMode)
    if (!inserted) {
      toast.error("Failed to insert HTML. Please check the markup.")
      return
    }

    toast.success(`HTML inserted (${insertMode})`)
  }

  const handleCopyRules = async () => {
    try {
      await navigator.clipboard.writeText(rulesText)
      toast.success("HTML rules copied for AI prompts")
    } catch {
      toast.error("Could not copy rules")
    }
  }

  return (
    <Card>
      <CardHeader>
        <CardTitle>AI HTML Assistant</CardTitle>
        <CardDescription>
          Supported HTML contract for this editor and quick insertion controls.
        </CardDescription>
      </CardHeader>
      <CardContent className="space-y-4">
        <details className="rounded-md border p-3">
          <summary className="cursor-pointer text-sm font-medium">Accepted HTML Rules (Comprehensive)</summary>
          <div className="mt-3 rounded-md bg-muted/40 p-3">
            <pre className="whitespace-pre-wrap wrap-break-word text-xs leading-5">{rulesText}</pre>
          </div>
          <div className="mt-3 flex justify-end">
            <Button type="button" variant="outline" size="sm" onClick={handleCopyRules}>
              Copy Rules For AI
            </Button>
          </div>
        </details>

        <div className="space-y-2">
          <Label htmlFor="editor-html-snippet">HTML Snippet</Label>
          <Textarea
            id="editor-html-snippet"
            value={htmlSnippet}
            onChange={(e) => setHtmlSnippet(e.target.value)}
            placeholder="Paste trusted HTML snippet"
            rows={10}
            className="max-h-80 min-h-40 resize-y overflow-y-auto font-mono text-xs"
          />
        </div>

        <div className="space-y-2">
          <Label>Insert Mode</Label>
          <RadioGroup
            value={insertMode}
            onValueChange={(value) => setInsertMode(value as HtmlInsertMode)}
            className="grid grid-cols-1 gap-3 sm:grid-cols-3"
          >
            <Label className="flex cursor-pointer items-center gap-2 rounded-md border p-3">
              <RadioGroupItem value="replace" id="editor-insert-mode-replace" />
              Replace all content
            </Label>
            <Label className="flex cursor-pointer items-center gap-2 rounded-md border p-3">
              <RadioGroupItem value="prepend" id="editor-insert-mode-prepend" />
              Prepend to top
            </Label>
            <Label className="flex cursor-pointer items-center gap-2 rounded-md border p-3">
              <RadioGroupItem value="append" id="editor-insert-mode-append" />
              Append to bottom
            </Label>
          </RadioGroup>
        </div>

        <div className="flex justify-end">
          <Button type="button" variant="outline" onClick={handleInsert}>
            Insert HTML
          </Button>
        </div>
      </CardContent>
    </Card>
  )
}
